# For technical reasons, this file is not reloaded automatically
# If you change this file, please restart the server process.

title: Natalia Farris
email: natalia.farris@interia.pl
description: >- # this means to ignore newlines until "baseurl:"
  Photography

tagline: >
  Photography Portfolio

hero_img: home/home.jpg

# Build settings
theme: jekyll-sleek
remote_theme:  janczizikow/sleek
markdown: kramdown
highlighter: rouge # or pygments or null

navigation:
  - { name: "About", link: "/about" }

include: ["_pages"]
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
